import type { Categoria, Colonia, Municipio } from "./types";

export const MUNICIPIOS_FOCO: Municipio[] = [
  { cveMun: "001", nombre: "Acapulco de Juárez", codigoFolio: "ACA" },
  { cveMun: "029", nombre: "Chilpancingo de los Bravo", codigoFolio: "CGO" },
  { cveMun: "038", nombre: "Zihuatanejo de Azueta", codigoFolio: "ZIH" },
  { cveMun: "055", nombre: "Taxco de Alarcón", codigoFolio: "TAX" },
  { cveMun: "021", nombre: "Coyuca de Benítez", codigoFolio: "COY" },
  { cveMun: "028", nombre: "Chilapa de Álvarez", codigoFolio: "CPA" },
  { cveMun: "035", nombre: "Iguala de la Independencia", codigoFolio: "IGU" },
  { cveMun: "057", nombre: "Técpan de Galeana", codigoFolio: "TEC" },
];

export const MUNICIPIO_POR_CVE = Object.fromEntries(
  MUNICIPIOS_FOCO.map((m) => [m.cveMun, m]),
) as Record<string, Municipio>;

export const COLONIAS_ACAPULCO: Colonia[] = [
  { id: "col-centro", nombre: "Centro", cveMun: "001", lat: 16.8494, lng: -99.9089 },
  { id: "col-diamante", nombre: "Diamante", cveMun: "001", lat: 16.794, lng: -99.818 },
  { id: "col-icacos", nombre: "Icacos", cveMun: "001", lat: 16.845, lng: -99.855 },
  { id: "col-pie", nombre: "Pie de la Cuesta", cveMun: "001", lat: 16.91, lng: -99.975 },
  { id: "col-sabana", nombre: "La Sabana", cveMun: "001", lat: 16.875, lng: -99.775 },
  { id: "col-renacimiento", nombre: "Renacimiento", cveMun: "001", lat: 16.89, lng: -99.85 },
  { id: "col-zapata", nombre: "Emiliano Zapata", cveMun: "001", lat: 16.86, lng: -99.88 },
  { id: "col-marques", nombre: "Puerto Marqués", cveMun: "001", lat: 16.804, lng: -99.845 },
  { id: "col-cayaco", nombre: "Cayaco", cveMun: "001", lat: 16.92, lng: -99.82 },
  { id: "col-colosio", nombre: "Colosio", cveMun: "001", lat: 16.88, lng: -99.89 },
  { id: "col-farallon", nombre: "Farallón", cveMun: "001", lat: 16.83, lng: -99.87 },
  { id: "col-hornos", nombre: "Hornos", cveMun: "001", lat: 16.852, lng: -99.875 },
];

export const COLONIA_POR_ID = Object.fromEntries(
  COLONIAS_ACAPULCO.map((c) => [c.id, c]),
) as Record<string, Colonia>;

export const CATEGORIAS: Categoria[] = [
  {
    id: "servicios",
    nombre: "Servicios públicos básicos",
    subcategorias: [
      "Agua potable — falta de suministro",
      "Agua potable — presión insuficiente",
      "Agua potable — calidad del agua",
      "Drenaje — falta de red",
      "Drenaje — obstrucción o mal funcionamiento",
      "Alcantarillado — coladeras tapadas",
      "Alumbrado público — luminarias fundidas",
      "Alumbrado público — falta de red",
      "Recolección de basura — servicio irregular",
      "Recolección de basura — no llega al domicilio",
      "Pavimentación — calles sin pavimentar",
      "Bacheo",
      "Banquetas y guarniciones",
      "Fugas de agua en la vía pública",
      "Otro (especificar)",
    ],
  },
  {
    id: "seguridad",
    nombre: "Seguridad pública",
    subcategorias: [
      "Presencia policial insuficiente",
      "Robo a casa habitación",
      "Robo a transeúnte o asalto",
      "Robo a comercio",
      "Extorsión y cobro de piso",
      "Violencia doméstica",
      "Violencia contra la mujer",
      "Feminicidio y su prevención",
      "Narcomenudeo",
      "Grupos delictivos en la zona",
      "Iluminación en zonas inseguras",
      "Cámaras de videovigilancia",
      "Puntos de reunión sospechosos",
      "Trata de personas",
      "Desapariciones",
      "Acoso callejero",
      "Otro (especificar)",
    ],
  },
  {
    id: "salud",
    nombre: "Salud",
    subcategorias: [
      "Ayudas funcionales — silla de ruedas",
      "Ayudas funcionales — bastón o muletas",
      "Ayudas funcionales — andadera",
      "Ayudas funcionales — pañales para adulto",
      "Ayudas funcionales — oxígeno portátil",
      "Ayudas funcionales — aparato auditivo",
      "Ayudas funcionales — prótesis",
      "Ayudas funcionales — lentes",
      "Medicamentos puntuales",
      "Consulta médica especializada",
      "Estudios médicos (laboratorio, imagen)",
      "Traslado médico a otra ciudad",
      "Apoyo para cirugía o intervención",
      "Salud mental y psicológica",
      "Adicciones — tratamiento y prevención",
      "Salud materna e infantil",
      "Enfermedades crónicas — seguimiento",
      "Infraestructura de salud — centro de salud",
      "Infraestructura de salud — desabasto general",
      "Infraestructura de salud — personal médico",
      "Servicios odontológicos",
      "Vacunación y prevención",
      "Otro (especificar)",
    ],
  },
  {
    id: "educacion",
    nombre: "Educación",
    subcategorias: [
      "Útiles escolares",
      "Uniformes escolares",
      "Calzado escolar",
      "Mochilas",
      "Becas educativas",
      "Inscripciones y trámites escolares",
      "Infraestructura — aulas",
      "Infraestructura — baños",
      "Infraestructura — techos y protección contra lluvia",
      "Infraestructura — bardas perimetrales",
      "Infraestructura — mobiliario escolar",
      "Plazas docentes — falta de maestros",
      "Guarderías y estancias infantiles",
      "Educación especial",
      "Transporte escolar",
      "Alimentación escolar (desayunos)",
      "Equipos de cómputo y conectividad",
      "Capacitación técnica y oficios",
      "Alfabetización para adultos",
      "Otro (especificar)",
    ],
  },
  {
    id: "empleo",
    nombre: "Empleo y economía familiar",
    subcategorias: [
      "Falta de empleo formal",
      "Apoyo a emprendedores",
      "Capacitación laboral",
      "Apoyos a comerciantes locales",
      "Tianguis y mercados — infraestructura",
      "Tianguis y mercados — regulación",
      "Empleo juvenil",
      "Apoyos a productores agrícolas",
      "Apoyos a pescadores",
      "Apoyos a artesanos",
      "Créditos productivos",
      "Bolsa de trabajo",
      "Apoyos por temporada baja",
      "Herramientas de trabajo",
      "Otro (especificar)",
    ],
  },
  {
    id: "vivienda",
    nombre: "Vivienda",
    subcategorias: [
      "Regularización de predios",
      "Escrituración",
      "Apoyos para construcción nueva",
      "Apoyos para mejora de vivienda",
      "Techos — láminas y materiales",
      "Pisos firmes",
      "Baños y sanitarios",
      "Servicios básicos en vivienda",
      "Riesgo estructural o daño por fenómeno natural",
      "Vivienda social",
      "Reubicación por zona de riesgo",
      "Cisternas y almacenamiento de agua",
      "Cocinas ecológicas",
      "Otro (especificar)",
    ],
  },
  {
    id: "movilidad",
    nombre: "Movilidad y transporte",
    subcategorias: [
      "Transporte público insuficiente",
      "Rutas de transporte — nuevas o modificación",
      "Semaforización",
      "Baches",
      "Señalización vial",
      "Ciclovías",
      "Transporte escolar",
      "Accesibilidad universal (rampas)",
      "Paraderos y parabuses",
      "Puentes peatonales",
      "Tarifas de transporte",
      "Servicio nocturno",
      "Caminos rurales — mantenimiento",
      "Otro (especificar)",
    ],
  },
  {
    id: "ambiente",
    nombre: "Medio ambiente",
    subcategorias: [
      "Tiraderos clandestinos",
      "Contaminación del aire",
      "Contaminación del agua (ríos, arroyos)",
      "Contaminación auditiva",
      "Áreas verdes — creación",
      "Áreas verdes — mantenimiento",
      "Poda de árboles",
      "Plagas urbanas (ratas, mosquitos)",
      "Quema de basura",
      "Cuerpos de agua — rescate y limpieza",
      "Manejo de residuos sólidos",
      "Protección de flora y fauna",
      "Erosión de suelos",
      "Otro (especificar)",
    ],
  },
  {
    id: "social",
    nombre: "Desarrollo social y apoyos",
    subcategorias: [
      "Programas sociales federales — gestión de acceso",
      "Programas sociales estatales — gestión de acceso",
      "Adultos mayores — apoyos",
      "Madres solteras — apoyos",
      "Personas con discapacidad — apoyos",
      "Comedores comunitarios",
      "Despensas alimentarias",
      "Migrantes — apoyos y gestión",
      "Pueblos indígenas — apoyos culturales",
      "Pueblos indígenas — gestión de derechos",
      "Personas en situación de calle",
      "Apoyos por desastre natural",
      "Ropa y calzado",
      "Enseres domésticos",
      "Otro (especificar)",
    ],
  },
  {
    id: "cultura",
    nombre: "Cultura, deporte y juventud",
    subcategorias: [
      "Espacios deportivos — mantenimiento",
      "Espacios deportivos — construcción",
      "Canchas deportivas",
      "Actividades culturales",
      "Casas de cultura",
      "Bibliotecas comunitarias",
      "Talleres artísticos",
      "Grupos culturales — apoyo",
      "Rescate de tradiciones locales",
      "Prevención de adicciones",
      "Actividades recreativas para jóvenes",
      "Actividades para niñez",
      "Ligas deportivas",
      "Torneos y competencias",
      "Otro (especificar)",
    ],
  },
  {
    id: "tramites",
    nombre: "Trámites y gestión municipal",
    subcategorias: [
      "Actas de nacimiento",
      "CURP",
      "Licencias de conducir",
      "Permisos comerciales",
      "Permisos de construcción",
      "Predial y trámites fiscales",
      "Atención en ventanillas — tiempos",
      "Atención en ventanillas — trato",
      "Denuncias contra funcionarios",
      "Transparencia y acceso a información",
      "Constancias y certificaciones",
      "Servicios catastrales",
      "Trámites del registro civil",
      "Otro (especificar)",
    ],
  },
  {
    id: "otros",
    nombre: "Otros",
    subcategorias: [
      "No aplica a ninguna categoría anterior",
      "Otro (especificar)",
    ],
  },
  {
    id: "apoyos",
    nombre: "Apoyos y eventos comunitarios",
    subcategorias: [
      "Fiestas patronales — banda o sonido",
      "Fiestas patronales — adornos y sillas",
      "Fiestas patronales — patrocinio general",
      "Eventos deportivos — patrocinio de torneo",
      "Eventos deportivos — uniformes",
      "Eventos deportivos — medallas y trofeos",
      "Viajes escolares — transporte",
      "Viajes escolares — viáticos",
      "Viajes escolares — seguros",
      "Materiales y uniformes escolares (evento)",
      "Transporte para grupos — cita médica masiva",
      "Transporte para grupos — asistencia a evento",
      "Transporte para grupos — trámites colectivos",
      "Patrocinios y donativos a colectivos",
      "Actividades religiosas — apoyo material",
      "Aniversarios comunitarios",
      "Kermeses y eventos de recaudación",
      "Otro (especificar)",
    ],
  },
];

export const CATEGORIA_POR_ID = Object.fromEntries(
  CATEGORIAS.map((c) => [c.id, c]),
) as Record<string, Categoria>;

export const TIPOS_PETICION = [
  { id: "queja", nombre: "Queja" },
  { id: "peticion", nombre: "Petición" },
  { id: "propuesta", nombre: "Propuesta" },
  { id: "requerimiento", nombre: "Requerimiento" },
  { id: "reconocimiento", nombre: "Reconocimiento" },
] as const;

export const URGENCIAS = [
  { id: "alta", nombre: "Alta" },
  { id: "media", nombre: "Media" },
  { id: "baja", nombre: "Baja" },
] as const;

export const ALCANCES = [
  { id: "individual", nombre: "Individual" },
  { id: "familiar", nombre: "Familiar" },
  { id: "colectivo", nombre: "Colectivo" },
] as const;

export const COMPLEJIDADES = [
  { id: "simple", nombre: "Simple" },
  { id: "media", nombre: "Media" },
  { id: "estructural", nombre: "Estructural" },
] as const;

export const RELACIONES_REMITENTE = [
  { id: "mismo", nombre: "El peticionario" },
  { id: "familiar", nombre: "Familiar" },
  { id: "vecino", nombre: "Vecino(a)" },
  { id: "representante", nombre: "Representante comunitario" },
  { id: "promotor", nombre: "Promotor" },
  { id: "no_especificada", nombre: "No especificada" },
] as const;

export const ESCENARIOS_ACUSE = [
  { id: "A", nombre: "A — acuse al peticionario" },
  { id: "B", nombre: "B — acuse al peticionario y aviso al intermediario" },
  { id: "C", nombre: "C — acuse en modo puente al intermediario" },
  { id: "D", nombre: "D — sin canal de acuse" },
] as const;

export const ORIGENES_CAPTURA = [
  { id: "escaneado_territorio", nombre: "Escaneado Territorio" },
  { id: "whatsapp_ciudadano", nombre: "WhatsApp ciudadano" },
] as const;

export const ESTATUS_PETICION = [
  { id: "recibida", nombre: "Recibida" },
  { id: "en_gestion", nombre: "En gestión" },
  { id: "cumplida", nombre: "Cumplida" },
  { id: "no_procede", nombre: "No procede" },
  { id: "compromiso_gobierno", nombre: "Compromiso de gobierno" },
  { id: "archivada", nombre: "Archivada" },
] as const;

export const ROL_LABEL: Record<string, string> = {
  territorio: "Capturista Territorio",
  cuantiva: "Capturista Cuantiva",
  candidata: "Candidata",
  admin: "Administrador",
};

export const HOME_POR_ROL: Record<string, string> = {
  territorio: "/territorio",
  cuantiva: "/bandeja",
  candidata: "/dashboard",
  admin: "/dashboard",
};
